### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by raolixiang-up** [dagleaves/ehull-calculator#1]
This is a great script. After I discovered it, I immediately tried using the example you provided. However, no output files were generated. Would it be convenient for you to provide some examples?

**Comment by dagleaves** [comment]
@raolixiang-up The issue was with the `--debug`` flag being auto-set to true. This has been fixed, as well as another bug I noticed while testing. I added the example .csv file for convenience. Thanks for catching that :)

**Comment by raolixiang-up** [comment]
Thank you for your reply. Firstly, you provided the API_key for Materials Project in the script, which is not secure.  Secondly, is the unit of energy above hull in the output file eV/atom? Finally, is it necessary to find a material that already knows the energy  above hull for testing, which can ensure the accuracy of the results. Thank you again for your reply and concise script. I hope my suggestions can provide you with useful references.

**Comment by dagleaves** [comment]
> cr

I thank you again for catching this mistake. In my hurry to release the fix, I did accidentally leave my API key in the repo. This has been removed and the history has been fixed. Thank you for notifying me of this!

To your other questions, yes the units for the output file are eV/atom. Regarding verification, if you run the program with the `--debug` flag, it will perform this verification for a sample of MP materials. This can be easily expanded by modifying the list in the script. If you are going from experimental materials not found in the MP database, it may be beneficial to perform this verification to be certain of the behavior.

I am not primarily a material scientist, so I cannot say with certainty that the behavior will be well-defined in all cases. However, the only way I can think that the results would be limited is through the scope of the Materials Project database. It would not be able to construct a phase diagram that includes competitive entries from experimental materials not found in the MP database if that is what you are working with. One of the material scientists in my group has also mentioned previously that there could be issues with using different VASP settings than MP uses, but we did not have that problem with our materials. I leave it to you to decide the best course of action for your use. If you require certainty for experimental materials, I would recommend using standard DFT methods, but performing the verification you describe would be a good way to check compatibility.

**Comment by raolixiang-up** [comment]
Thanks for your reply. It is difficult to grasp the accuracy of using Pymatgen and Materiasl Project database to calculate energy above hull of specific materials. Furthermore, the issue of energy correction is also a significant influencing factor, and the literature rarely improves these details. However, energy correction has a significant impact on the results, which has been tested by us. For energy correction, refer to the following link: https://docs.materialsproject.org/methodology/materials-methodology/thermodynamic-stability/thermodynamic-stability.
In addition, it is also a question whether energy correction is required for the items we want to calculate and how to perform energy correction. Thanks again for your reply, which has greatly benefited me.
